basePath: /
host: localhost:5000
info:
  contact: {}
  description: Zyosa Api with Go Fiber
  title: Zyosa API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Returns a simple hello message
      produces:
      - application/json
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      summary: Root Endpoint
      tags:
      - Root
swagger: "2.0"
